name: saltech_web
description: Our company website.
  All the products that we're made them or are making now.

version: 1.0.12

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  animated_icon_button: ^1.0.2
  flutter_translate: ^4.0.4
  material_symbols_icons: ^4.2668.0
  retrofit: ^4.0.1
  dio: ^5.3.2
  built_value: ^8.6.2
  json_annotation: ^4.8.1
  url_launcher: ^6.1.14
  firebase_core: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  built_value_generator: ^8.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/

  fonts:
    - family: Peyda
      fonts:
        - asset: assets/fonts/Peyda-Thin.ttf
          weight: 100
        - asset: assets/fonts/Peyda-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Peyda-Light.ttf
          weight: 300
        - asset: assets/fonts/Peyda-Regular.ttf
          weight: 400
        - asset: assets/fonts/Peyda-Medium.ttf
          weight: 500
        - asset: assets/fonts/Peyda-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Peyda-Bold.ttf
          weight: 700
        - asset: assets/fonts/Peyda-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Peyda-Black.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VF.ttf
        - asset: assets/fonts/RobotoMono-VF-Italic.ttf
          style: italic

    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
